#!/bin/bash

set -o errexit
set -o nounset

worker_ready() {
    celery -A etermax_api_service inspect ping
}

until worker_ready; do
  >&2 echo 'Celery workers not available'
  sleep 60
done
>&2 echo 'Celery workers is available'

celery flower \
    -A pickup_points \
    --broker="${BROKER_URL}" \
    --basic_auth="${CELERY_FLOWER_USER}:${CELERY_FLOWER_PASSWORD}"
