version: '3.9'

services:
  etermax-api-service:
    container_name: etermax_api_service
    build:
      context: .
      dockerfile: compose/local/django/Dockerfile
    restart: always
    command: /start
    volumes:
      - ./etermax_api_service:/app
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
      - redis
    networks:
      etermax-network:
    stdin_open: true
    tty: true

  redis:
    container_name: redis
    image: redis:7.2.5-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/root/redis
      - redis.conf:/usr/local/etc/redis/redis.conf
    env_file:
      - .env
    networks:
      etermax-network:

  celery:
    container_name: celery
    build:
      context: .
      dockerfile: compose/local/django/Dockerfile
    command: /start-celeryworker
    volumes:
      - ./etermax_api_service:/app
    env_file:
      - .env
    depends_on:
      - redis
      - etermax-api-service
    networks:
      etermax-network:

  celery-beat:
    container_name: celery-beat
    build:
      context: .
      dockerfile: compose/local/django/Dockerfile
    command: /start-celerybeat
    env_file:
      - .env
    volumes:
      - ./etermax_api_service:/app
    depends_on:
      - redis
      - etermax-api-service
    networks:
      etermax-network:

volumes:
  etermax-api-service:
  redis_data:
  redis.conf:

networks:
  etermax-network:
